#######
# SITE SETTINGS
#
# title appears in the header
title: SS-CITOSSES
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: code-slash
# description, keywords, and image for meta tags
# these do not visibility appear on the pages, but used for SEO
description: "Special Session: Computational Intelligence Techniques for Observable Smart Grid and Sustainable Energy Systems @ WCCI 2024, Yokohama, Japan!"
keywords: "special session, websites, gh-pages, jekyll"
# featured-image is added to metadata tags for social media sharing
# use a relative path to image in this repository or full URL
featured-image: "/images/large_yokahoma_japan_2248134426.jpg"
# add search box to footer? true/false
search: false

# author settings for cc-by, appears in the footer and credits
author: Djordje Batic
# your github username for link [optional]
github_username: djordjebatic
# year or date published
pub_year: 2023
# location of code, the full url to your github repository
source-code: https://github.com/djordjebatic/djordjebatic.github.io

##########
# URL VARIABLES [optional!!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
# When using github pages just leave these blank!
#
# use url for the domain, e.g. https://evanwill.github.io
# on gh-pages follow the pattern: https://username.github.io
url:
# use baseurl to add subsection of the domain, e.g. /workshop-template-b
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl: /wcci-citosses



##########
# GOOGLE ANALYTICS [optional!]
#
# leave this blank or comment out to NOT include google code
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
google-analytics-id:

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
